#!/usr/bin/python

import argparse
import collections
import datetime
import json
import math
import sys
import time
import urlparse

import requests  # http://python-requests.org
import toml      # https://github.com/uiri/toml

start_time = time.time()

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--verbose', action='store_true', help='Be verbose about script actions.')
parser.add_argument(      '--debug', action='store_true', help='Enable debugging output.')
parser.add_argument('-c', '--config', type=argparse.FileType('r'), help='File containing parameters for connecting to an OpenHAB instance.')
parser.add_argument('-H', '--host', help='Name of the host running OpenHAB.  Defaults to localhost.')
parser.add_argument('-p', '--port', help='Port on which to connect to OpenHAB host.  Defaults to 80 for HTTP and 443 for HTTPS.')
parser.add_argument('-s', '--ssl', action='store_const', const=True, help='Use SSL for this connection.')
parser.add_argument(      '--no-ssl', action='store_const', const=False, dest='ssl', help='Do not use SSL for this connection.')
parser.add_argument(      '--start', type=int, help='Starting value for the item.  If unset, the item\'s current value will be used.')
parser.add_argument(      '--end', type=int, help='Ending value for the item.')
parser.add_argument(      '--duration', type=int, help='Duration of time, in seconds.')
parser.add_argument(      '--step', type=int, help='Target step increment for intermediate values.  Defaults to 1.')
parser.add_argument(      '--item', help='Name of the item to modify.')
parser.add_argument('script', nargs='?', type=argparse.FileType('r'), help='Script to run.')
parsed_args = parser.parse_args()

def is_nonstring_sequence(obj):
    if isinstance(obj, basestring):
        return False
    return isinstance(obj, collections.Sequence)

class Config:
    def __init__(self, parsed_args):
        if parsed_args.config is not None:
            config_args = toml.load(parsed_args.config)
        elif parsed_args.script is not None:
            config_args = toml.load(parsed_args.script)
        else:
            config_args = {}

        if parsed_args.host is not None:
            self.rest_hostname = parsed_args.host
        elif 'rest' in config_args and 'host' in config_args['rest']:
            self.rest_hostname = config_args['rest']['host']
        else:
            self.rest_hostname = 'localhost'

        if parsed_args.ssl is not None:
            self.rest_ssl = parsed_args.ssl
        elif 'rest' in config_args and 'ssl' in config_args['rest']:
            if config_args['rest']['ssl'] not in (True, False):
                print >>sys.stderr, 'rest.ssl config must be "true" or "false"'
                exit(1)
            self.rest_ssl = config_args['rest']['ssl']
        else:
            self.rest_ssl = False
            
        if parsed_args.port is not None:
            self.rest_port = parsed_args.port
        elif 'rest' in config_args and 'port' in config_args['rest']:
            if not isinstance(config_args['rest']['port'], (int, long)):
                print >>sys.stderr, 'rest.port config must be an integer'
                exit(1)
            self.rest_port = config_args['rest']['port']
        elif self.rest_ssl:
            self.rest_port = 443
        else:
            self.rest_port = 80

        self.verbose = parsed_args.verbose or parsed_args.debug
        self.debug = parsed_args.debug

class ItemChange:
    @staticmethod
    def from_toml(config, toml_dict, init_time):
        if 'start_time' in toml_dict:
            start_time = init_time + toml_dict['start_time']
        else:
            start_time = init_time
            
        if 'duration' in toml_dict:
            end_time = start_time + toml_dict['duration']
        else:
            end_time = start_time
            
        if 'start_value' in toml_dict:
            start_value = toml_dict['start_value']
        else:
            start_value = None

        end_value = toml_dict['end_value']
        step = toml_dict['step'] if 'step' in toml_dict else None
            
        if start_time == end_time:
            return ItemSet(config, toml_dict['item'], end_time, end_value)
        else:
            if not is_nonstring_sequence(end_value):
                end_value = (end_value,)
                if start_value is not None:
                    start_value = (start_value,)
                if step is not None:
                    step = (step,)
            return ItemChange(config,
                              toml_dict['item'],
                              (start_time, end_time),
                              (start_value, end_value),
                              step)
    
    def __init__(self, config, item_name, time_bounds, value_bounds, steps=None):
        # Basics
        self.config = config
        self.item_name = item_name
        self.start_time, self.end_time = time_bounds
        self.start_values, self.end_values = value_bounds
        self.steps = steps
        
        self.started = False
        self.current_values = None
        
        if self.start_values is not None:
            self.calculate_params()

    def __repr__(self):
        return '<ItemChange({}: {}..{} {}-{})>'.format(self.item_name, self.start_values, self.end_values, self.start_time, self.end_time)

    @property
    def formatted_info(self):
        return (time.strftime('%H:%M:%S', time.localtime(self.start_time)), time.strftime('%H:%M:%S', time.localtime(self.end_time)), self.item_name, ','.join([str(v) for v in self.start_values]) if self.start_values is not None else '', ','.join([str(v) for v in self.end_values]))
    
    def set_current_value_from_openhab(self):
        r = requests.get(self.item_url)
        r.raise_for_status()
        s = json.loads(r.text)
        if s['type'] == 'Color' and len(self.end_values) == 1:
            self.current_values = int(s['state'].split(',')[-1])
        else:
            self.current_values = [int(v) for v in s['state'].split(',')]
        if self.config.verbose:
            print '{} {}: fetched current state {}'.format(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'), self.item_name, self.current_values)

    def calculate_params(self):
        if self.steps is None:
            self.steps = [ math.copysign(1, ev - sv) for (sv, ev) in zip(self.start_values, self.end_values) ]
            
        # Check step direction, fix if necessary.
        implied_steps = [ math.copysign(1, ev - sv) for (sv, ev) in zip(self.start_values, self.end_values) ]
        if self.steps != implied_steps:
            print >>sys.stderr, '{}: {}..{} sign(s) mismatch: requested {}, but should be {}.'.format(self.item_name, self.start_values, self.end_values, self.steps, implied_steps)
            self.steps = implied_steps

        # Set value limits
        self.min_values = [ sv if step > 0 else ev for (sv, ev, step) in zip(self.start_values, self.end_values, self.steps) ]
        self.max_values = [ ev if step > 0 else sv for (sv, ev, step) in zip(self.start_values, self.end_values, self.steps) ]

        # Set linear equation coefficients.
        # y = mx + b
        # In this case,
        #   y = item value
        #   x = time
        #   desired_value = slope * time.time() + intercept
        self.slopes = [ (ev - sv) / (self.end_time - self.start_time) for (sv, ev) in zip(self.start_values, self.end_values) ]
        self.intercepts = [ sv - slope * self.start_time for (sv, slope) in zip(self.start_values, self.slopes) ]
        if self.config.debug:
            print self.item_name + ':'
            for (i, (slope, intercept)) in enumerate(zip(self.slopes, self.intercepts)):
                print '  y_{} = {} * x_{} + {}'.format(i, slope, i, intercept)
        
    @property
    def item_url(self):
        return urlparse.urlunsplit(('https' if self.config.rest_ssl else 'http','{}:{}'.format(self.config.rest_hostname, self.config.rest_port), '/rest/items/{}'.format(self.item_name), None, None))

    @property
    def time_to_next_step(self):
        if not self.started:
            # Not yet started; next time we have to do something is our start time.
            next_time = self.start_time
        elif self.current_values is None or self.end_time <= time.time():
            # Somehow we've started, but haven't set a value yet.  Or it's
            # past our end time.  Either way, do something now.
            return 0
        else:
            # How long will it be before we next need to update?
            next_values = [ cv + step for cv, step in zip(self.current_values, self.steps) ]
            next_times = [ (nv - intercept) / slope if slope != 0 else float('inf') for nv, intercept, slope in zip(next_values, self.intercepts, self.slopes) ]
            next_time = min(next_times)
        return max(0, next_time - time.time())
        
    def set_item(self):
        # Don't do anything if we're not supposed to start yet.
        if time.time() < self.start_time:
            return
        self.started = True
        if self.end_time <= time.time():
            clamped_values = self.end_values
        else:
            # If the starting value is unset, pull it from the current state on OpenHAB.
            if self.start_values is None:
                self.set_current_value_from_openhab()
                self.start_values = self.current_values
                self.calculate_params()
            ref_time = time.time()
            clamped_values = [min(max(int(round(slope * ref_time + intercept)),
                                      min_value),
                                  max_value)
                              for slope, intercept, min_value, max_value
                              in zip(self.slopes, self.intercepts, self.min_values, self.max_values)]
        if clamped_values != self.current_values:
            r = requests.post(self.item_url, ','.join([str(cv) for cv in clamped_values]))
            r.raise_for_status()
            self.current_values = clamped_values
            if self.config.verbose:
                print '{} {}: {}'.format(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'), self.item_name, self.current_values)

class ItemSet:
    """When an item is set once."""
    
    def __init__(self, config, item_name, set_time, set_value):
        # Basics
        self.config = config
        self.item_name = item_name
        self.set_time = set_time
        if is_nonstring_sequence(set_value):
            self.set_value = ','.join([str(v) for v in set_value])
        else:
            self.set_value = str(set_value)

        # Compatibility
        self.start_time = self.set_time
        self.end_time = self.set_time
        
        self.has_been_set = False

    def __repr__(self):
        return '<ItemSet({}: {} {})>'.format(self.item_name, self.set_value, self.set_time)

    @property
    def formatted_info(self):
        return (time.strftime('%H:%M:%S', time.localtime(self.set_time)), '', self.item_name, '', self.set_value)
    
    @property
    def item_url(self):
        return urlparse.urlunsplit(('https' if self.config.rest_ssl else 'http','{}:{}'.format(self.config.rest_hostname, self.config.rest_port), '/rest/items/{}'.format(self.item_name), None, None))

    @property
    def time_to_next_step(self):
        return max(0, self.set_time - time.time())
        
    def set_item(self):
        if not self.has_been_set:
            r = requests.post(self.item_url, self.set_value)
            r.raise_for_status()
            self.has_been_set = True
            if self.config.verbose:
                print '{} {}: {}'.format(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'), self.item_name, self.set_value)
                
config = Config(parsed_args)

if parsed_args.script is not None:
    if parsed_args.start is not None or \
       parsed_args.end is not None or \
       parsed_args.duration is not None or \
       parsed_args.step is not None or \
       parsed_args.item is not None:
        print >>sys.stderr, '--item is mutually exclusive with giving a script.'
        exit(1)
    parsed_args.script.seek(0)
    changes = []
    for c in toml.load(parsed_args.script)['changes']:
        changes.append(ItemChange.from_toml(config, c, start_time))
else:
    end_time = start_time + parsed_args.duration
    changes = [ItemChange(config, parsed_args.item, (start_time, end_time), (parsed_args.start, parsed_args.end), parsed_args.step)]

changes.sort(key=lambda c: (c.start_time, c.end_time, c.item_name))
if config.verbose:
    change_info = [c.formatted_info for c in changes]
    col_widths = [max([len(v) for v in col]) for col in zip(*change_info)]
    print '-+-'.join(['-' * w for w in col_widths])
    for c in change_info:
        print ' | '.join([v.ljust(w) for w, v in zip(col_widths, c)])
    print '-+-'.join(['-' * w for w in col_widths])
    
foo = 0
last_end_time = max([c.end_time for c in changes])
while time.time() < last_end_time:
    # Fixed time reference so all comparisons will be on equal footing.
    loop_start = time.time()
    need_to_prune = False
    for c in changes:
        if loop_start < c.start_time:
            continue
        c.set_item()
        need_to_prune = need_to_prune or c.end_time <= loop_start
    if need_to_prune:
        changes = [c for c in changes if loop_start < c.end_time]
    sleep_time = min([c.time_to_next_step for c in changes])
    if config.debug:
        print '--- Sleeping for {}s.'.format(sleep_time)
    if sleep_time == 0:
        print loop_start, time.time()
        for c in changes:
            print c, c.time_to_next_step
        if foo > 0:
            exit(2)
        foo += 1
    time.sleep(sleep_time)

# Ensure that the final values were hit.
for c in changes:
    c.set_item()
